frameworkVersion: ">=1.50.0"
service: sayhello
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  tags:
    project: serverlesspracticalway
functions:
  helloWorld:
    handler: handler.helloWorld
    description: 'Return a helloWorld'
  sayHello:
    handler: handler.sayHello
    description: 'Return a hello to the name provided @params: {name}'